
import jinja2

envi = jinja2.Environment()


template = envi.from_string("Hello, {{ name }}!")

print(template.render(name="husnu"))


from jinja2 import Environment, FileSystemLoader

envi = Environment(loader=FileSystemLoader("templates/"))
template = envi.get_template("message.txt")

# from dataclasses import dataclass


# @dataclass
# class Student:
#     name: str
#     score: int

students = [
    dict(name="Joe", score=100),
    dict(name="Bob", score=87),
    dict(name="Jane", score=92),
    dict(name="Fritz", score=40),
    dict(name="Sirius", score=75),
]
max_score = 120
test_name = "python temPlating challange"


def sort_fn(d: dict):
    return d["score"]


for s in students:

    content = template.render(s, max_score=max_score, test_name=test_name)

    print(content)
    print()

dean = envi.get_template("dean.md")

content = dean.render(
    students=students, max_score=max_score, test_name=test_name
)

with open("autogenerated.md", "w") as f:
    print(content, file=f)
